name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - '14.x'  
          - '16.x'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: |
          npm ci --legacy-peer-deps  
          npm install react-scripts  
          npm run build  
