name: Node.js CI

on:
  push:
    branches:
      - main  # Changed branch name from 'master' to 'main'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - '14.x'  # Use a version that matches the supported React version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: |
          npm ci --legacy-peer-deps  # Ensure dependencies are installed
          npm install react-scripts  # Install react-scripts if missing
          npm run build  # Run the build command
